# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.

  config.vm.hostname = "doboto-sandbox"
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "doboto_sandbox" do |doboto_sandbox|
  end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../../doboto", "/home/vagrant/doboto"
  config.ssh.forward_agent = true

  # Use VM Fusion by default but virtual box is fine too
  config.vm.provider "virtualbox"
  config.vm.provider "vmware_fusion"

  # If we're using Virtual Box
  config.vm.provider "virtualbox" do |vb|

    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provision.yml"
  end

end
